# Generated by Django 3.0.8 on 2020-08-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_category_viz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='viz',
            field=models.TextField(),
        ),
    ]
