# Generated by Django 3.0.8 on 2020-08-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20200821_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='viz',
            field=models.TextField(blank=True),
        ),
    ]
